<?php

namespace Database\Seeders;

use App\Models\State;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class StateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $now = Carbon::now();
        State::insert([
            [
                'name' => 'Alabama',
                'code' => 'AL',
                'coefficient' => 0.4741,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Alaska',
                'code' => 'AK',
                'coefficient' => 0.4376,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Arizona',
                'code' => 'AZ',
                'coefficient' => 0.4591,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Arkansas',
                'code' => 'AR',
                'coefficient' => 0.4750,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'California',
                'code' => 'CA',
                'coefficient' => 0.4866,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Colorado',
                'code' => 'CO',
                'coefficient' => 0.4548,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Connecticut',
                'code' => 'CT',
                'coefficient' => 0.5024,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Delaware',
                'code' => 'DE',
                'coefficient' => 0.4509,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'District of Columbia',
                'code' => 'DC',
                'coefficient' => 0.5115,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Florida',
                'code' => 'FL',
                'coefficient' => 0.4808,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Georgia',
                'code' => 'GA',
                'coefficient' => 0.4795,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Hawaii',
                'code' => 'HI',
                'coefficient' => 0.4397,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Idaho',
                'code' => 'ID',
                'coefficient' => 0.4337,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Illinois',
                'code' => 'IL',
                'coefficient' => 0.4800,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Indiana',
                'code' => 'IN',
                'coefficient' => 0.4584,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Iowa',
                'code' => 'IA',
                'coefficient' => 0.4422,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Kansas',
                'code' => 'KS',
                'coefficient' => 0.4500,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Kentucky',
                'code' => 'KY',
                'coefficient' => 0.4764,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Louisiana',
                'code' => 'LA',
                'coefficient' => 0.4978,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Maine',
                'code' => 'ME',
                'coefficient' => 0.4490,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Maryland',
                'code' => 'MD',
                'coefficient' => 0.4558,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Massachusetts',
                'code' => 'MA',
                'coefficient' => 0.4803,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Michigan',
                'code' => 'MI',
                'coefficient' => 0.4634,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Minnesota',
                'code' => 'MN',
                'coefficient' => 0.4434,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Mississippi',
                'code' => 'MS',
                'coefficient' => 0.4896,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Missouri',
                'code' => 'MO',
                'coefficient' => 0.4633,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Montana',
                'code' => 'MT',
                'coefficient' => 0.4597,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Nebraska',
                'code' => 'NE'
                , 'coefficient' => 0.4400,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Nevada',
                'code' => 'NV',
                'coefficient' => 0.4710,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'New Hampshire',
                'code' => 'NH',
                'coefficient' => 0.4406,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'New Jersey',
                'code' => 'NJ',
                'coefficient' => 0.4782,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'New Mexico',
                'code' => 'NM',
                'coefficient' => 0.4768,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'New York',
                'code' => 'NY',
                'coefficient' => 0.5149,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'North Carolina',
                'code' => 'NC',
                'coefficient' => 0.4743,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'North Dakota',
                'code' => 'ND',
                'coefficient' => 0.4558,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Ohio',
                'code' => 'OH',
                'coefficient' => 0.4651,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Oklahoma',
                'code' => 'OK',
                'coefficient' => 0.4739,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Oregon',
                'code' => 'OR',
                'coefficient' => 0.4500,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Pennsylvania',
                'code' => 'PA',
                'coefficient' => 0.4745,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Puerto Rico',
                'code' => 'PR',
                'coefficient' => 0.5509,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Rhode Island',
                'code' => 'RI',
                'coefficient' => 0.4628,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'South Carolina',
                'code' => 'SC',
                'coefficient' => 0.4747,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'South Dakota',
                'code' => 'SD',
                'coefficient' => 0.4360,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Tennessee',
                'code' => 'TN',
                'coefficient' => 0.4749,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Texas',
                'code' => 'TX',
                'coefficient' => 0.4753,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Utah',
                'code' => 'UT',
                'coefficient' => 0.4268,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Vermont',
                'code' => 'VT',
                'coefficient' => 0.4471,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Virginia',
                'code' => 'VA',
                'coefficient' => 0.4690,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Washington',
                'code' => 'WA',
                'coefficient' => 0.4577,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'West Virginia',
                'code' => 'WV',
                'coefficient' => 0.4644,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Wisconsin',
                'code' => 'WI',
                'coefficient' => 0.4391,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Wyoming',
                'code' => 'WY',
                'coefficient' => 0.4345,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);
    }
}
